name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: |
          cd angular-portfolio
          npm install

      - name: Build
        run: |
          cd angular-portfolio
          npm run build -- --base-href=/Angular_portfolio_2/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: angular-portfolio/dist/angular-portfolio/browser
          branch: gh-pages
